### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Johnathon332** [TargetProcess/signalr-client-py#18]
I get a socket.error: [Errno 104] Connection reset by peer after two metrics and not sure why this is happening.  I read around and it says that the server has forcefully shut down the connection, however nowhere in my signalr hub does that happen.  Here is the full stack trace 

`Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pika/adapters/twisted_connection.py", line 38, in put
    return defer.DeferredQueue.put(self, obj)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1515, in put
    self.waiting.pop(0).callback(obj)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "IBus.py", line 142, in <lambda>
    return d.addCallback(lambda result: self.handle_payload(*result))
  File "IBus.py", line 265, in handle_payload
    self.medium.server.invoke('Send', method.delivery_tag, metric_type, json.dumps(data))
  File "/usr/local/lib/python2.7/site-packages/signalr/hubs/_hub.py", line 23, in invoke
    'I': self.__connection.increment_send_counter()
  File "/usr/local/lib/python2.7/site-packages/signalr/_connection.py", line 63, in send
    self.__transport.send(data)
  File "/usr/local/lib/python2.7/site-packages/signalr/transports/_auto_transport.py", line 31, in send
    self.__transport.send(data)
  File "/usr/local/lib/python2.7/site-packages/signalr/transports/_ws_transport.py", line 48, in send
    self.ws.send(json.dumps(data))
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 239, in send
    return self.send_frame(frame)
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 264, in send_frame
    l = self._send(data)
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 425, in _send
    return send(self.sock, data)
  File "/usr/local/lib/python2.7/site-packages/websocket/_socket.py", line 112, in send
    return sock.send(data)
  File "/usr/local/lib/python2.7/site-packages/gevent/_socket2.py", line 320, in send
    return sock.send(data, flags)
socket.error: [Errno 104] Connection reset by peer`

At first I thought it could have been because the message I am trying to send is too big, however having read the signalr github page, this does not seem to be the case.

**Comment by mhamzashahid** [comment]
Its the server fault it had to close the connection after each call.

**Comment by minhtuan221** [comment]
I have the same problem here. After I took time to research, I found that because of Connection Timeout. For example, place a row `time.sleep(16)` in your handler function (that mean you stall it for 16 second). You will see the error thrown
