### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by muthusabarinathan** [TargetProcess/signalr-client-py#43]
Hi,
I got this error from signalr-client and unable to catch the exception as well.Can you please help me to fix the issue

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gevent/greenlet.py", line 536, in run
    result = self._run(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/signalr/_connection.py", line 53, in wrapped_listener
    listener()
  File "/usr/lib/python2.7/site-packages/signalr/transports/_ws_transport.py", line 42, in _receive
    for notification in self.ws:
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 108, in __iter__
    yield self.recv()
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 300, in recv
    opcode, data = self.recv_data()
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 317, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 330, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 364, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/usr/lib/python2.7/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 434, in _recv
    return recv(self.sock, bufsize)
  File "/usr/lib/python2.7/site-packages/websocket/_socket.py", line 81, in recv
    bytes_ = sock.recv(bufsize)
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 458, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/site-packages/gevent/_sslgte279.py", line 314, in read
    return self._sslobj.read(len or 1024)
error: [Errno 104] Connection reset by peer
Tue Jul 17 08:22:31 2018 <Greenlet at 0xb559fb20L: wrapped_listener> failed with error

**Comment by desstannoz** [comment]
I have same problem

**Comment by rbrook** [comment]
Same problem here.
Anyone got a solution? @desstannoz , @muthusabarinathan 
Thanks!

**Comment by minhtuan221** [comment]
I have the same problem here. After I took time to research, I found that because of Connection Timeout. For example, place a row `time.sleep(16)` in your handler function (that mean you stall it for 16 second). You will see the error thrown
