### ISSUE TITLE
HTTPS error

### ISSUE THREAD

**Issue by hassanrazakhalid** [TargetProcess/signalr-client-py#49]
hi
im trying to make a connection by im getting error. Please guide how to fix this. i tried the sample code

from requests import Session
from signalr import Connection

```
class SignalR:


    def start_connection(self):
        with Session() as session:
            #create a connection
            connection = Connection("https://localhost:5001", session)

            #get chat hub
            chat = connection.register_hub('contentHub')

            #start a connection
            connection.start()

            #create new chat message handler
            def print_received_message(data):
                print('received: ', data)

            #create new chat topic handler
            def print_topic(topic, user):
                print('topic: ', topic, user)

            #create error handler
            def print_error(error):
                print('error: ', error)

            #receive new chat messages from the hub
            chat.client.on('newMessageReceived', print_received_message)

            #change chat topic
            chat.client.on('topicChanged', print_topic)

            #process errors
            connection.error += print_error

            #start connection, optionally can be connection.start()
            with connection:

                #post new message
                chat.server.invoke('send', 'Python is here')

                #change chat topic
                chat.server.invoke('setTopic', 'Welcome python!')

                #invoke server method that throws error
                chat.server.invoke('requestError')

                #post another message
                chat.server.invoke('send', 'Bye-bye!')

                #wait a second before exit
                # connection.wait(1)
```

```
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gevent/monkey.py:783: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util.ssl_ (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/ssl_.py)', 'urllib3.util (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/__init__.py)']. 
  _warnings)
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    conn.start_connection();
  File "/Volumes/Data/hardstone_projects/nuc-client/signalR_listener.py", line 17, in start_connection
    connection.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/signalr/_connection.py", line 47, in start
    negotiate_data = self.__transport.negotiate()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/signalr/transports/_auto_transport.py", line 16, in negotiate
    negotiate_data = Transport.negotiate(self)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/signalr/transports/_transport.py", line 26, in negotiate
    negotiate = self._session.get(url)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connection.py", line 332, in connect
    cert_reqs=resolve_cert_reqs(self.cert_reqs),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 281, in create_urllib3_context
    context.options |= options
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 323 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by dzervas** [comment]
Instead of 
```
from requests import Session
from signalr import Connection
```
do:
```
from signalr import Connection
from requests import Session
```

**Comment by nlazardi** [comment]
I have this code but i have this error:

from signalr import Connection
from requests import Session

token = 'XXXXXXXXXXXX'

with Session() as session:

    #create a connection
    connection = Connection("https://www.XXXXX/signalr", Session)

    #get chat hub
    chat = connection.register_hub('JoinGroup({token})'.format(token=token))

    #start a connection
    connection.start()


error:
             TypeError: get() missing 1 required positional argument: 'url'
